### ISSUE TITLE
Cannot connect to the db

### ISSUE THREAD

**Issue by Norticus36** [gerazo/eltelive#11]
the page does not react to the register or to the login buttons, the server part also gets the following error message:
server running on port 4000
(node:34021) UnhandledPromiseRejectionWarning: MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (/home/x/Desktop/eltelive/eltelive-new/node_modules/mongoose/lib/connection.js:694:11)
    at /home/x/Desktop/eltelive/eltelive-new/node_modules/mongoose/lib/index.js:351:10
    at /home/x/Desktop/eltelive/eltelive-new/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/home/x/Desktop/eltelive/eltelive-new/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Mongoose._promiseOrCallback (/home/x/Desktop/eltelive/eltelive-new/node_modules/mongoose/lib/index.js:1149:10)
    at Mongoose.connect (/home/x/Desktop/eltelive/eltelive-new/node_modules/mongoose/lib/index.js:350:20)
    at Object.<anonymous> (/home/x/Desktop/eltelive/eltelive-new/db_connections/db.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/x/Desktop/eltelive/eltelive-new/server.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:34021) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:34021) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Ubuntu 20.04.3

**Comment by Norticus36** [comment]
Note: we should also double check if the .env file was set up properly (as indicated in the other issue, the setup process was ambigious)

**Comment by Norticus36** [comment]
The issue was related to the .env file, see issue #9
